name: React.js Package

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  # release:
  #   types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: cd packages/components
      - run: rm -rf node_modules
      - run: yarn install --frozen-lockfile
      - run: yarn compile
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_API_TOKEN }}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: cd packages/components
      - run: rm -rf node_modules
      - run: yarn install --frozen-lockfile
      - run: yarn compile
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
