name: Deploy Storybook

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        working-directory: ./packages/components
        run: |
          rm -rf node_modules
          yarn install --frozen-lockfile
      - name: Build static Storybook
        working-directory: ./packages/components
        run: yarn build-storybook
      - name: Deploy Storybook
        working-directory: ./packages/components
        run: yarn deploy-storybook -- --ci --host-token-env-variable=GITHUB_TOKEN
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
