name: React publish to NPM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        working-directory: ./packages/components
        run: |
          rm -rf node_modules
          yarn install --frozen-lockfile
      - name: Lint and test
        working-directory: ./packages/components
        run: |
          yarn lint
          yarn test
      - name: Build package
        working-directory: ./packages/components
        run: yarn compile

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Publish package to NPM
        working-directory: ./packages/components
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_API_TOKEN }}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Publish package to GPR
        working-directory: ./packages/components
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
